---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d86b84eda2ce30015257928/webhook/forestry'
sections:
  - type: document
    label: Site Metadata
    path: _data/metadata.json
    templates:
      - metadata
  - type: document
    label: Home
    path: pages/home.md
    templates:
      - home
  - type: directory
    path: pages
    match: '**/*'
    exclude: '{home.md,blog.md,contact.md,pages/home.md,pages/blog.md,pages/contact.md}'
    label: Page
    create: all
    templates:
      - page
  - type: document
    label: Blog Post
    path: pages/blog.md
    templates:
      - blog
  - type: document
    label: Contact
    path: pages/contact.md
    templates:
      - contact
  - type: directory
    path: posts
    match: '**/*'
    label: Post
    create: all
    templates:
      - post
  - type: document
    label: 404 Page
    path: 404.md
    templates:
      - not_found
upload_dir: static/img
public_path: /img
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
